App/Portal/Controllers/MemberController.cs
using Portal.Models.MemberModels;
using Portal.Models.MemberModels.MemberListModels;
using Portal.Provider;
using Portal.Repositories;
using System;
using System.Web.Mvc;
using Newtonsoft.Json;
using Portal.Models.MemberModels.MemberSaveModels;

namespace Portal.Controllers
{
    public class MemberController : BaseController
    {
        private MemberRepository m_memberRepository = new MemberRepository();
        private MemberRepository Repository { get { return this.m_memberRepository; } set { this.m_memberRepository = value; } }

        [HttpGet]
        public ActionResult MemberList(int? page, string qry, string target)
        {
            MemberListViewFilterCollectionModel filterCollectionModel = null;
            var filterCol = Request.QueryString["filterCol"];
            if (!string.IsNullOrEmpty(filterCol))
                filterCollectionModel = JsonConvert.DeserializeObject<MemberListViewFilterCollectionModel>(filterCol);

            MemberListViewModel model = new MemberListViewModel();
            model.Filter.FilterTargetStr = target;
            model.Filter.QueryString = qry;
            model.Filter.CurrentPage = page ?? 1;
            model.Result = this.Repository.GetMemberList(model.Filter);
            ViewBag.Targer = target;
            ViewBag.SearchStr = qry;
            ViewBag.FilterCollection = filterCollectionModel;
            return View(model);
        }

        [HttpGet]
        public ActionResult MemberAdd()
        {
            return View();
        }

        [HttpPost]
        public ActionResult MemberAdd(MemberDataModel model)
        {
            Exception error = null;
            MemberDataModel result = new MemberDataModel();
            try
            {
                result = this.Repository.MemberSave(model, Enums.DataSaveMode.Add);
                if (result == null)
                    throw new Exception("新增使用者失敗");
            }
            catch (Exception ex)
            {
                error = ex;
            }

            if (error != null)
            {
                ViewBag.AddFail = error.Message;
                return View();
            }
            return RedirectToAction("MemBerEdit", new { empID = result.EmpID });
        }

        [HttpGet]
        public ActionResult MemberEdit(string empID)
        {
            MemberDataModel model = new MemberDataModel();
            try
            {
                if (string.IsNullOrEmpty(empID))
                    empID = SignInProvider.Instance.User.ID;
                model = this.Repository.GetMemberDataByID(empID);
            }
            catch (Exception ex)
            {
                ViewBag.AddFail = ex.Message;
            }
            finally
            {
                ViewBag.depList = this.Repository.GetProtoDepartmentDataToSelectList();
                ViewBag.roleList = this.Repository.GetProtoRoleDataToSelectList();
            }
            return View(model);
        }

        [HttpPost]
        public ActionResult MemberEdit(MemberDataModel model)
        {
            MemberDataModel result = new MemberDataModel();
            try
            {
                result = this.Repository.MemberSave(model, Enums.DataSaveMode.Edit);
                if (result == null)
                    throw new Exception("更新使用者失敗");
            }
            catch (Exception ex)
            {
                ViewBag.AddFail = ex.Message;
            }
            finally
            {
                ViewBag.depList = this.Repository.GetProtoDepartmentDataToSelectList();
                ViewBag.roleList = this.Repository.GetProtoRoleDataToSelectList();
            }
            ViewBag.AddSuccess = "Success";
            return View(model);
        }

        [HttpPost]
        public ActionResult MemberDelete(string memberID)
        {
            return View();
        }
    }
}

App/Portal/Controllers/MenuController.cs
using Portal.Models.MenuModels.MenuListModels;
using Portal.Models.MenuModels.MenuSaveModels;
using Portal.Repositories;
using System;
using System.Web.Mvc;

namespace Portal.Controllers
{
    public class MenuController : BaseController
    {
        private MenuRepository m_menuRepository = new MenuRepository();
        private MenuRepository Repository { get { return this.m_menuRepository; } set { this.m_menuRepository = value; } }

        [HttpGet]
        public ActionResult MenuList(int? page, string qry, string target)
        {
            MenuListViewModel model = new MenuListViewModel();
            model.Filter.FilterTargetStr = target;
            model.Filter.QueryString = qry;
            model.Filter.CurrentPage = page ?? 1;
            model.Result = this.Repository.GetMenuList(model.Filter);
            ViewBag.Targer = target;
            ViewBag.SearchStr = qry;
            return View(model);
        }

        [HttpGet]
        public ActionResult MenuAdd()
        {
            return View(new MenuDataModel() { Enabled = true, MenuSort = 0 });
        }

        [HttpPost]
        public ActionResult MenuAdd(MenuDataModel model)
        {
            Exception error = null;
            MenuDataModel result = new MenuDataModel();
            try
            {
                result = this.Repository.MenuSave(model, Enums.DataSaveMode.Add);
                if (result == null)
                    throw new Exception("新增目錄失敗");
            }
            catch (Exception ex)
            {
                error = ex;
            }

            if (error != null)
            {
                ViewBag.AddFail = error.Message;
                return View(model);
            }
            else
                ViewBag.AddFail = "success";

            return RedirectToAction("MenuEdit", new { muID = result.MenuID });
        }

        [HttpGet]
        public ActionResult MenuEdit(string muID)
        {
            if (string.IsNullOrEmpty(muID))
                throw new Exception("查無該目錄");
            MenuDataModel result = this.Repository.GetMenuByID(muID);
            return View(result);
        }

        [HttpPost]
        public ActionResult MenuEdit(MenuDataModel model)
        {
            MenuDataModel result = new MenuDataModel();
            try
            {
                result = this.Repository.MenuSave(model, Enums.DataSaveMode.Edit);
                if (result == null)
                    throw new Exception("更新目錄失敗");
            }
            catch (Exception ex)
            {
                throw ex;
            }
            TempData["ResultMsg"] = "success";
            return RedirectToAction("MenuEdit", new { muID = result.MenuID });
        }

        /// <summary>
        /// 新增一筆根目錄
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult SubMenuAdd(SubMenuDataModel model)
        {
            Exception error = null;
            try
            {
                bool result = this.Repository.SubMenuSave(model, Enums.DataSaveMode.Add);
            }
            catch (Exception ex)
            {
                error = ex;
            }

            if (error != null)
                TempData["ResultMsg"] = error.Message;
            else
                TempData["ResultMsg"] = "success";

            return RedirectToAction("MenuEdit", new { muID = model.SubMenuID });
        }




        /// <summary>
        /// 刪除目錄
        /// </summary>
        /// <param name="muID"></param>
        /// <returns></returns>
        [HttpPost]
        public JsonResult MenuDelete(string muID)
        {
            bool success = true;
            string msg = string.Empty;
            try
            {
                success = this.Repository.DeleteMenuByID(muID);
                msg = "success";
            }
            catch (Exception ex)
            {
                msg = ex.Message; ;
                success = false;
            }
            return Json(new { success = success, msg = msg });
        }
    }
}

App/Portal/Views/Shared/_MasterLayout - 複製.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - 我的 ASP.NET 應用程式</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("應用程式名稱", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("首頁", "Index", "Home")</li>
                    <li>@Html.ActionLink("關於", "About", "Home")</li>
                    <li>@Html.ActionLink("連絡方式", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - 我的 ASP.NET 應用程式</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

App/Portal/Views/Shared/_MasterLayout.cshtml
@using Portal.Provider
@using Portal.CustomHtmlHelper
<!DOCTYPE html>
<html lang="en">
@{

    string controllerName = Convert.ToString(HttpContext.Current.Request.RequestContext.RouteData.Values["Controller"]);
    string actionName = Convert.ToString(HttpContext.Current.Request.RequestContext.RouteData.Values["Action"]);

}
<head>
    <title>@ViewBag.Title - Portal</title>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/mainJs")
    @Styles.Render("~/Content/mainCss")
    @RenderSection("IncludeCSS", false)
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,700,800' rel='stylesheet' type='text/css'>
    <style>
        /*左側menu選單子項目 原架構的submenu會無法對子目錄下的子目錄作動畫展開，所以自訂coustom-submenu來做margin*/
        .coustom-submenu > ul > li {
            margin-left: 30%;
        }

        /*左側選單的label已被框架指定為紅色 強制改變顏色*/
        #sidebar > ul > li > a > .label {
            background-color: #00b900 !important;
        }
        /*.submenu ul li {
            margin-left: 21%;
        }*/
        #breadcrumb a.current {
            font-weight: bold;
            color: gray;
        }
    </style>
</head>
<body>

    <!--Header-part-->
    <div id="header">
        <h1><a href="dashboard.html">Matrix Admin</a></h1>
    </div>
    <!--close-Header-part-->
    <!--top-Header-menu-->
    <div id="user-nav" class="navbar navbar-inverse">
        <ul class="nav">
            <li class="dropdown" id="profile-messages">
                <a title="" href="#" data-toggle="dropdown" data-target="#profile-messages" class="dropdown-toggle"><i class="icon icon-user"></i>  <span class="text">您好! @SignInProvider.Instance.User.Name</span><b class="caret"></b></a>
                <ul class="dropdown-menu">
                    <li><a href="#"><i class="icon-user"></i> My Profile</a></li>
                    <li class="divider"></li>
                    <li><a href="#"><i class="icon-check"></i> My Tasks</a></li>
                    <li class="divider"></li>
                    <li><a href="@Url.Action("Logout", "Account")"><i class=" icon-key"></i> 登出</a></li>
                </ul>
            </li>
            <li class="dropdown" id="menu-messages">
                <a href="#" data-toggle="dropdown" data-target="#menu-messages" class="dropdown-toggle"><i class="icon icon-envelope"></i> <span class="text">Messages</span> <span class="label label-important">5</span> <b class="caret"></b></a>
                <ul class="dropdown-menu">
                    <li><a class="sAdd" title="" href="#"><i class="icon-plus"></i> new message</a></li>
                    <li class="divider"></li>
                    <li><a class="sInbox" title="" href="#"><i class="icon-envelope"></i> inbox</a></li>
                    <li class="divider"></li>
                    <li><a class="sOutbox" title="" href="#"><i class="icon-arrow-up"></i> outbox</a></li>
                    <li class="divider"></li>
                    <li><a class="sTrash" title="" href="#"><i class="icon-trash"></i> trash</a></li>
                </ul>
            </li>
            <li class=""><a title="" href="#"><i class="icon icon-cog"></i> <span class="text">Settings</span></a></li>
            <li class=""><a title="" href="@Url.Action("Logout", "Account")"><i class="icon icon-share-alt"></i> <span class="text">登出</span></a></li>
        </ul>
    </div>

    <!--start-top-serch-->
    <div id="search">
        <input type="text" placeholder="Search here..." />
        <button type="submit" class="tip-bottom" title="Search"><i class="icon-search icon-white"></i></button>
    </div>
    <!--close-top-serch-->
    <!--sidebar-menu-->
    <div id="sidebar">
        <a href="#" class="visible-phone"><i class="icon icon-tint"></i>Buttons &amp; icons</a>
        <ul>

            @if (SignInProvider.Instance.User != null)
            {
                foreach (var mu in SignInProvider.Instance.User.MenuList)
                {
                    if (mu.Enabled)
                    {
                        @Html.SubMenuHandler(mu)
                    }

                }
            }

            @*<li class="submenu">
                    <a href="#"><i class="icon icon-user"></i> <span>使用者管理</span> <span class="label label-important">3</span></a>
                    <ul>
                        <li><a href="@Url.Action("MemberList", "Member")">使用者列表</a></li>
                        <li><a href="@Url.Action("MemberAdd", "Member")">使用者新增</a></li>
                        <li class="submenu">
                            <a href="#"><i class="icon icon-user"></i> <span>使用者管理</span> <span class="label label-important">3</span></a>
                            <ul>
                                <li><a href="@Url.Action("MemberList", "Member")">使用者列表</a></li>
                                <li><a href="@Url.Action("MemberAdd", "Member")">使用者新增</a></li>
                                <li><a href="@Url.Action("MemberEdit", "Member")">使用者編輯</a></li>
                            </ul>
                        </li>
                    </ul>
                </li>*@

                @*<li class="submenu">
                            <a href="#"><i class="icon icon-user"></i> <span>使用者管理</span> <span class="label label-important">3</span></a>
                            <ul>
                                <li><a href="@Url.Action("MemberList", "Member")">使用者列表</a></li>
                                <li><a href="@Url.Action("MemberAdd", "Member")">使用者新增</a></li>
                                <li><a href="@Url.Action("MemberEdit", "Member")">使用者編輯</a></li>
                            </ul>
                        </li>

                        <li><a href="@Url.Action("RoleList", "Role")"><i class=" icon icon-signal"></i> <span>角色管理</span></a> </li>
                        <li><a href="@Url.Action("MenuList", "Menu")"><i class=" icon icon-road"></i> <span>目錄管理</span></a> </li>
                    <li><a href="@Url.Action("MenuList", "Menu")"><i class=" icon icon-road"></i> <span>目錄管理</span></a> </li>*@
            </ul>
        </div>

        <!--main-container-part-->
        <div id="content">
            <div id="content-header">
                <!--site map 麵包屑-->
                <div id="breadcrumb">
                    @Html.Breadcrumb(controllerName, actionName)
                    @*<a href="#" title="Go to Home" class="tip-bottom"><i class="icon-home"></i> Home</a>
                    <a href="#" class="current">Buttons &amp; icons</a>*@
                </div>
                @*<h1>Buttons &amp; icons</h1>*@
            </div>

            <div class="container-fluid">
                @RenderBody()
            </div>
        </div>
        <!--End-main-container-part-->
        <!--Footer-part-->
        <!--Footer-part-->
        <div class="row-fluid">
            <div id="footer" class="span12"> 2013 &copy; Matrix Admin. Brought to you by <a href="http://themedesigner.in">Themedesigner.in</a> </div>
        </div>
        <!--end-Footer-part-->
        <!--end-Footer-part-->
        @RenderSection("IncludeJS", required: false)
        <script>
            $(function () {
                $('.submenu').click(function () {
                    var $findll = $('#sidebar').find('li');
                    $findll.each(function () {
                        $(this).removeClass('active');
                    });
                    //$(this).addClass('active');
                    $(this).removeClass('submenu').addClass('active');
                });
            })
        </script>
    </body>
</html>